import { ArrowRight, BookOpen, Calculator, CheckCircle2, ChevronLeft, GraduationCap, LockKeyhole, Play, Target } from "lucide-react";
import { useState } from "react";

const SUBJECTS = {
  bm: { title: "Bahasa Melayu", english: "Malay", Icon: BookOpen, items: [{ title: "Huruf", text: "Kenal huruf besar dan kecil", href: "/murid/bahasa-melayu" }, { title: "Vokal", text: "Dengar dan kenal bunyi vokal", href: "/murid/bahasa-melayu" }, { title: "Suku kata", text: "Latihan KV dan KVK", href: "/kvk" }, { title: "Perkataan", text: "Bina dan kenal perkataan", href: "/murid/bahasa-melayu" }, { title: "Sebutan", text: "Dengar dan sebut", href: "/murid/bahasa-melayu" }] },
  math: { title: "Matematik", english: "Mathematics", Icon: Calculator, items: [{ title: "Tambah", text: "Bina dan kumpul nombor", href: "/addition-regroup" }, { title: "Tolak", text: "Ambil dan kira", href: "/minus-regroup" }, { title: "Darab", text: "Kumpulan sama banyak", href: "/mosquito-splat?op=darab" }, { title: "Bahagi", text: "Kongsi sama rata", href: null }] }
};

export default function TeacherHub({ initialSubject = "bm" }) {
  const [subject, setSubject] = useState(initialSubject); const data = SUBJECTS[subject];
  const Icon = data.Icon;
  return <main className="teacher-page"><header className="teacher-header"><a href="/" className="portal-back" aria-label="Kembali / Back"><ChevronLeft size={20} /></a><div className="portal-logo"><span>A</span><span>1</span><span>*</span></div><div><span className="portal-kicker">Ruang panduan / Guide space</span><strong>Cikgu & ibu bapa</strong></div><span className="teacher-badge"><GraduationCap size={16} /> Teacher / Parent</span></header><section className="teacher-content"><div className="teacher-intro"><span className="portal-eyebrow"><Target size={16} /> Sedia untuk belajar bersama?</span><h1>Pilih aktiviti untuk anak</h1><p>Choose an activity, then explore it together with your learner.</p></div><div className="teacher-subject-tabs" role="tablist">{Object.entries(SUBJECTS).map(([id, item]) => { const SubjectIcon = item.Icon; return <button key={id} className={subject === id ? "is-active" : ""} type="button" role="tab" aria-selected={subject === id} onClick={() => setSubject(id)}><SubjectIcon size={19} /> {item.title}<small>{item.english}</small></button>; })}</div><div className="teacher-layout"><section className="teacher-activity-panel"><div className="section-heading-row"><div><span className="section-kicker">Aktiviti / Activities</span><h2><Icon size={22} /> {data.title}</h2></div><span className="skill-count"><CheckCircle2 size={15} /> {data.items.length} pilihan</span></div><div className="teacher-activity-list">{data.items.map((item, index) => <div className={`teacher-activity ${!item.href ? "is-locked" : ""}`} key={item.title}><span className="teacher-number">{String(index + 1).padStart(2, "0")}</span><span className="teacher-activity-copy"><strong>{item.title}</strong><span>{item.text}</span></span>{item.href ? <a href={item.href} aria-label={`Buka ${item.title}`}><Play size={16} fill="currentColor" /> Buka / Open <ArrowRight size={15} /></a> : <span className="teacher-coming"><LockKeyhole size={15} /> Akan datang / Coming soon</span>}</div>)}</div></section><aside className="teacher-guide"><span className="section-kicker">Panduan ringkas / Quick guide</span><h2>Perhatikan langkah anak</h2><ul><li><strong>Latih</strong><span>Biarkan anak cuba dahulu.</span></li><li><strong>Tanya</strong><span>“Bunyi apa yang kamu dengar?”</span></li><li><strong>Raikan</strong><span>Puji usaha, bukan hanya jawapan betul.</span></li></ul><div className="teacher-tip"><Target size={17} /><span>Tip: Beri masa untuk anak berfikir sebelum membantu.</span></div></aside></div></section></main>;
}
